### PR TITLE
Crypto: Revisions and test harness updates

### PR DESCRIPTION
**Pull request by jas-**
Please not that while two of the three tests function correctly. There is a bug with the supplied existing client object for the third test preventing encryption/decryption of session data.

### CODE REVIEW

**Comment by balor** [comment]
Thank you, I'll investigate this last case and report.

**Comment by jas-** [comment]
> Thank you, I'll investigate this last case and report.

I found it, give me a minute to update the PR.

**Comment by jas-** [comment]
@balor Ok, the last commit resolves all issues.

**Comment by jas-** [comment]
@balor as an FYI, I ran the test harness on a clean install for node versions 12-16 and they all worked great.

I did notice that your module supports all versions greater than v0.10.x. The new dependency only supports versions >8 but this is only because one particular [test](https://github.com/jas-/kruptein/blob/19519bb7386cdea96663e662c99b9d742b160879/test/index.js#L126) uses some math that isn’t supported in versions <8.

That being said, the kruptein module functionality should work all the way back to v4 and greater. I can’t guarantee anything earlier than that

**Pull request merged**
